import { expect, jest, test } from '@jest/globals';
import { createTelemetryCollector } from '../../src/telemetry/collector.mjs';
test('accepts client reports and summarizes them on demand', () => { const collector = createTelemetryCollector({ now: () => 1000, setIntervalImpl: jest.fn(() => ({ unref() {} })), clearIntervalImpl: jest.fn() }); expect(collector.accept({ type: 'client.telemetry', application: 'app', queries: 2, failures: 1, avgLatencyMs: 5, inflight: 1 })).toBe(true); expect(collector.accept({ type: 'bad', application: 'app' })).toBe(false); expect(collector.summarize()).toMatchObject({ clients: 1, queries: 2, failures: 1, avgLatencyMs: 5 }); collector.start(); collector.stop(); });
test('normalizes sparse telemetry reports and rejects malformed applications', () => { const collector = createTelemetryCollector({ now: () => 1000 }); expect(collector.accept({ type: 'client.telemetry' })).toBe(false); expect(collector.accept({ type: 'client.telemetry', application: 'sparse' })).toBe(true); expect(collector.summarize()).toMatchObject({ clients: 1, queries: 0, failures: 0, retries: 0, reconnects: 0, failoverCount: 0, inflight: 0, avgLatencyMs: 0 }); });
test('does not create duplicate timers and safely stops when idle', () => { const clear = jest.fn(); const collector = createTelemetryCollector({ setIntervalImpl: () => ({ unref() {} }), clearIntervalImpl: clear }); collector.start(); collector.start(); collector.stop(); collector.stop(); expect(clear).toHaveBeenCalledTimes(1); });
test('provides default collector configuration', () => { const collector = createTelemetryCollector(); expect(collector.summary()).toMatchObject({ clients: 0, queries: 0 }); expect(collector.accept({ type: 'client.telemetry', application: 'default' })).toBe(true); });
test('expires clients that stop reporting and never emits NaN', () => { let now = 1000; const collector = createTelemetryCollector({ intervalMs: 100, now: () => now }); expect(collector.accept({ type: 'client.telemetry', application: 'app', queries: 'bad', avgLatencyMs: Infinity })).toBe(true); expect(collector.summarize()).toMatchObject({ clients: 1, queries: 0, avgLatencyMs: 0 }); now = 1401; expect(collector.summarize()).toMatchObject({ clients: 0, queries: 0, avgLatencyMs: 0 }); });
test('exposes per-application detail and null for unknown applications', () => { const collector = createTelemetryCollector({ now: () => 1000 }); collector.accept({ type: 'client.telemetry', application: 'app', queries: 3 }); expect(collector.details('app')).toMatchObject({ application: 'app', queries: 3 }); expect(collector.details('missing')).toBeNull(); expect(collector.details()).toHaveLength(1); });
test('summarizes supervisor lifecycle events without retaining client details', () => { const collector = createTelemetryCollector({ now: () => 1000 }); collector.recordEvent(); collector.recordEvent('traffic.drain'); collector.recordEvent('lifecycle.draining'); collector.recordEvent('traffic.drain'); expect(collector.summarize()).toMatchObject({ lifecycleEvents: { 'traffic.drain': 2, 'lifecycle.draining': 1 } }); });
