import { expect, jest, test } from '@jest/globals';
import { handleManagedRoute } from '../src/api/routes/managed.mjs';

const request = (body = {}) => ({ url: 'http://localhost/api?v=1&application=app', async *[Symbol.asyncIterator]() { if (Object.keys(body).length) yield JSON.stringify(body); } });
const context = (method, path, body = {}) => { const response = { json: jest.fn() }; const managed = { listDatabases: jest.fn(async () => ['app']), listIdentities: jest.fn(async () => []), createDatabase: jest.fn(async () => ({ database: 'app' })), createIdentity: jest.fn(async () => ({ identity: 'id' })), rotateIdentity: jest.fn(async () => ({})), issueToken: jest.fn(async () => ({})), revokeToken: jest.fn(async () => ({})), revokeIdentity: jest.fn(async () => ({})) }; return { method, path, request: request(body), response, managed, auth: { scopes: ['metadata:read', 'database:read', 'database:provision', 'identity:read', 'identity:provision', 'identity:rotate', 'token:create', 'token:revoke', 'identity:revoke'] } }; };
test('handles all managed metadata, database, identity, and token routes', async () => { const routes = [['GET', '/api/v1/metadata/export'], ['GET', '/api/v1/databases'], ['POST', '/api/v1/databases', { application: 'app', database: 'app' }], ['GET', '/api/v1/identities'], ['POST', '/api/v1/identities', { application: 'app', database: 'app', identity: 'id' }], ['POST', '/api/v1/identities/rotate', { identity: 'id' }], ['POST', '/api/v1/tokens', { name: 't' }], ['POST', '/api/v1/tokens/revoke', { name: 't' }], ['POST', '/api/v1/identities/revoke', { identity: 'id' }]]; for (const [method, path, body] of routes) { const c = context(method, path, body); expect(await handleManagedRoute(c)).toBe(true); expect(c.response.json).toHaveBeenCalled(); expect(await handleManagedRoute({ ...context(method, path, body), auth: { scopes: [] } })).toBe(false); } expect(await handleManagedRoute({ ...context('GET', '/api/v1/databases'), auth: { root: true } })).toBe(true); expect(await handleManagedRoute({ ...context('GET', '/api/v1/identities'), request: { url: 'http://localhost', async *[Symbol.asyncIterator]() { throw new Error('bad body'); } } })).toBe(true); expect(await handleManagedRoute({ ...context('GET', '/other'), managed: undefined })).toBe(false); });
test('rejects scoped routes when the optional scope collection is absent', async () => { const c = context('GET', '/api/v1/databases'); expect(await handleManagedRoute({ ...c, auth: {} })).toBe(false); });
test('rejects managed access when authentication is absent', async () => { const c = context('GET', '/api/v1/databases'); expect(await handleManagedRoute({ ...c, auth: undefined })).toBe(false); });
test('uses the databaseName fallback when database is omitted', async () => { const c = context('POST', '/api/v1/databases', { application: 'app', database: null, databaseName: 'fallback' }); expect(await handleManagedRoute(c)).toBe(true); });
