import { createHash, randomBytes } from 'node:crypto';
import { identifier, literal } from '../accounts/sql.mjs';
import { createSecretBox } from './secret-box.mjs';
import { validateGrantPolicy } from '../accounts/grant-policy.mjs';
import { clientSqlAddress } from '../routing/client-address.mjs';
import { tokenMatchesHash } from './token-authentication.mjs';

const name = (value, label) => { if (typeof value !== 'string' || !/^[A-Za-z][A-Za-z0-9_-]{0,62}$/.test(value)) throw Object.assign(new Error(`${label} is invalid`), { statusCode: 400 }); return value; };
const hash = (value) => createHash('sha256').update(value).digest('hex');
const password = () => randomBytes(24).toString('base64url');

export function createManagedMetadata({ query, database = 'elera_meta', credentialKey = process.env.ELERA_CREDENTIAL_KEY } = {}) {
  if (typeof query !== 'function') throw new TypeError('query function is required');
  const q = (sql, params) => query(sql.replaceAll('elera_meta', `\`${database}\``), params);
  const box = credentialKey ? createSecretBox(credentialKey) : null;
  return {
    async createDatabase({ application, databaseName }) { name(application, 'application'); name(databaseName, 'database'); await q(`INSERT INTO elera_meta.applications (name) VALUES (${literal(application)}) ON DUPLICATE KEY UPDATE name=name`); await q(`INSERT INTO elera_meta.managed_databases (name, application_name) VALUES (${literal(databaseName)}, ${literal(application)}) ON DUPLICATE KEY UPDATE application_name=VALUES(application_name)`); await query(`CREATE DATABASE IF NOT EXISTS ${identifier(databaseName)}`); return { application, database: databaseName }; },
    async listDatabases() { const [rows] = await q('SELECT name, application_name AS application, created_at FROM elera_meta.managed_databases ORDER BY name'); return rows; },
    async createIdentity({ application, databaseName, identity, purpose = 'runtime', grants = [] }) { name(application, 'application'); name(databaseName, 'database'); name(identity, 'identity'); if (!['runtime', 'readonly', 'migration', 'reporting', 'admin'].includes(purpose)) throw Object.assign(new Error('identity purpose is invalid'), { statusCode: 400 }); if (!box) throw new Error('credential encryption is not configured'); const username = `${application}_${identity}`; const secret = password(); grants.forEach(validateGrantPolicy); await this.createDatabase({ application, databaseName }); await q(`INSERT INTO elera_meta.identities (name, application_name, purpose, database_name, username, credential_ciphertext) VALUES (${literal(identity)}, ${literal(application)}, ${literal(purpose)}, ${literal(databaseName)}, ${literal(username)}, ${literal(box.seal(secret))}) ON DUPLICATE KEY UPDATE purpose=VALUES(purpose), database_name=VALUES(database_name), credential_ciphertext=VALUES(credential_ciphertext), active=TRUE`); await q(`INSERT INTO elera_meta.grants_policy (identity_name, grants_json) VALUES (${literal(identity)}, ${literal(JSON.stringify(grants))}) ON DUPLICATE KEY UPDATE grants_json=VALUES(grants_json)`); await query(`CREATE USER IF NOT EXISTS ${literal(username)}@'%' IDENTIFIED BY ${literal(secret)}`); await query(`ALTER USER ${literal(username)}@'%' IDENTIFIED BY ${literal(secret)}`); await query(`REVOKE ALL PRIVILEGES, GRANT OPTION FROM ${literal(username)}@'%'`); for (const grant of grants) await query(`GRANT ${grant} ON ${identifier(databaseName)}.* TO ${literal(username)}@'%'`); await query('FLUSH PRIVILEGES'); return { application, database: databaseName, identity, purpose, username, password: secret, grants }; },
    async listIdentities(application) { const filter = application ? ` WHERE i.application_name = ${literal(application)}` : ''; const [rows] = await q(`SELECT i.name, i.application_name AS application, i.purpose, i.database_name AS database, i.username, i.active, i.created_at, g.grants_json FROM elera_meta.identities i LEFT JOIN elera_meta.grants_policy g ON g.identity_name = i.name${filter} ORDER BY i.name`); return rows.map(({ grants_json, ...row }) => ({ ...row, grants: Array.isArray(grants_json) ? grants_json : JSON.parse(grants_json ?? '[]') })); },
    async revokeIdentity(identity) { await q(`UPDATE elera_meta.identities SET active=FALSE WHERE name=${literal(identity)}`); return { identity, revoked: true }; },
    async rotateIdentity(identity) { name(identity, 'identity'); if (!box) throw new Error('credential encryption is not configured'); const secret = password(); const [rows] = await q(`SELECT username FROM elera_meta.identities WHERE name=${literal(identity)} AND active=TRUE`); const username = rows[0]?.username; if (!username) throw Object.assign(new Error('identity not found'), { statusCode: 404 }); await q(`UPDATE elera_meta.identities SET credential_ciphertext=${literal(box.seal(secret))} WHERE name=${literal(identity)}`); await query(`ALTER USER ${literal(username)}@'%' IDENTIFIED BY ${literal(secret)}`); await query('FLUSH PRIVILEGES'); return { identity, username, password: secret, rotated: true }; },
    async lease({ identity, routes = {}, nodeIdentity, ports }) { name(identity, 'identity'); if (!box) throw new Error('credential encryption is not configured'); const [rows] = await q(`SELECT application_name AS application, database_name AS database, username, credential_ciphertext FROM elera_meta.identities WHERE name=${literal(identity)} AND active=TRUE`); const row = rows[0]; if (!row) throw Object.assign(new Error('identity not found'), { statusCode: 404 }); const primary = routes.primary ?? [{ host: clientSqlAddress(process.env), port: 3306, nodeId: nodeIdentity ?? 'local' }]; return { application: row.application, database: row.database, identity, username: row.username, password: box.open(row.credential_ciphertext), routes: { primary, balanced: routes.balanced ?? primary }, nodeIdentity, ports, expiresAt: new Date(Date.now() + 3600000).toISOString() }; },
    async issueToken({ tokenName, application, identity, scopes = [] }) { name(tokenName, 'token'); name(application, 'application'); name(identity, 'identity'); const [rows] = await q(`SELECT application_name AS application, database_name AS database FROM elera_meta.identities WHERE name=${literal(identity)} AND active=TRUE`); const owner = rows[0]; if (!owner) throw Object.assign(new Error('identity not found'), { statusCode: 404 }); if (owner.application !== application) throw Object.assign(new Error('identity does not belong to application'), { statusCode: 400 }); const secret = randomBytes(32).toString('base64url'); await q(`INSERT INTO elera_meta.scoped_tokens (name, token_hash, application_name, identity_name, scopes_json) VALUES (${literal(tokenName)}, ${literal(hash(secret))}, ${literal(application)}, ${literal(identity)}, ${literal(JSON.stringify(scopes))}) ON DUPLICATE KEY UPDATE token_hash=VALUES(token_hash), active=TRUE, rotated_at=CURRENT_TIMESTAMP`); return { name: tokenName, token: secret, application, database: owner.database, identity, scopes }; },
    async revokeToken(tokenName) { name(tokenName, 'token'); await q(`UPDATE elera_meta.scoped_tokens SET active=FALSE WHERE name=${literal(tokenName)}`); return { name: tokenName, revoked: true }; },
    async authenticate(token) { if (!token) return null; const [rows] = await q('SELECT t.name, t.application_name AS application, i.database_name AS database, t.identity_name AS identity, t.token_hash, t.scopes_json FROM elera_meta.scoped_tokens t LEFT JOIN elera_meta.identities i ON i.name=t.identity_name AND i.application_name=t.application_name WHERE t.active=TRUE'); const row = rows.find((candidate) => tokenMatchesHash(token, candidate.token_hash)); if (!row) return null; const { token_hash: _tokenHash, scopes_json: scopesJson, ...metadata } = row; return { ...metadata, scopes: Array.isArray(scopesJson) ? scopesJson : JSON.parse(scopesJson ?? '[]') }; }
  };
}
