import { createHash, randomBytes } from 'node:crypto';
import { identifier, literal } from '../accounts/sql.mjs';

const name = (value, label) => { if (typeof value !== 'string' || !/^[A-Za-z][A-Za-z0-9_-]{0,62}$/.test(value)) throw Object.assign(new Error(`${label} is invalid`), { statusCode: 400 }); return value; };
const hash = (value) => createHash('sha256').update(value).digest('hex');
const password = () => randomBytes(24).toString('base64url');

export function createManagedMetadata({ query, database = 'elera_meta' } = {}) {
  if (typeof query !== 'function') throw new TypeError('query function is required');
  const q = (sql, params) => query(sql.replaceAll('elera_meta', `\`${database}\``), params);
  return {
    async createDatabase({ application, databaseName }) { name(application, 'application'); name(databaseName, 'database'); await q(`INSERT INTO elera_meta.applications (name) VALUES (${literal(application)}) ON DUPLICATE KEY UPDATE name=name`); await q(`INSERT INTO elera_meta.managed_databases (name, application_name) VALUES (${literal(databaseName)}, ${literal(application)}) ON DUPLICATE KEY UPDATE application_name=VALUES(application_name)`); await query(`CREATE DATABASE IF NOT EXISTS ${identifier(databaseName)}`); return { application, database: databaseName }; },
    async listDatabases() { const [rows] = await q('SELECT name, application_name AS application, created_at FROM elera_meta.managed_databases ORDER BY name'); return rows; },
    async createIdentity({ application, databaseName, identity, purpose = 'runtime', grants = [] }) { name(application, 'application'); name(databaseName, 'database'); name(identity, 'identity'); if (!['runtime', 'readonly', 'migration', 'reporting', 'admin'].includes(purpose)) throw Object.assign(new Error('identity purpose is invalid'), { statusCode: 400 }); const username = `${application}_${identity}`; const secret = password(); await this.createDatabase({ application, databaseName }); await q(`INSERT INTO elera_meta.identities (name, application_name, purpose, database_name, username) VALUES (${literal(identity)}, ${literal(application)}, ${literal(purpose)}, ${literal(databaseName)}, ${literal(username)}) ON DUPLICATE KEY UPDATE purpose=VALUES(purpose), database_name=VALUES(database_name), active=TRUE`); await q(`INSERT INTO elera_meta.grants_policy (identity_name, grants_json) VALUES (${literal(identity)}, ${literal(JSON.stringify(grants))}) ON DUPLICATE KEY UPDATE grants_json=VALUES(grants_json)`); await query(`CREATE USER IF NOT EXISTS ${literal(username)}@'%' IDENTIFIED BY ${literal(secret)}`); await query(`REVOKE ALL PRIVILEGES, GRANT OPTION FROM ${literal(username)}@'%'`); for (const grant of grants) { if (typeof grant !== 'string' || !/^(SELECT|INSERT|UPDATE|DELETE|EXECUTE|CREATE|ALTER|INDEX|REFERENCES)(,\s*(SELECT|INSERT|UPDATE|DELETE|EXECUTE|CREATE|ALTER|INDEX|REFERENCES))*$/i.test(grant)) throw Object.assign(new Error('invalid grant policy'), { statusCode: 400 }); await query(`GRANT ${grant} ON ${identifier(databaseName)}.* TO ${literal(username)}@'%'`); } await query('FLUSH PRIVILEGES'); return { application, database: databaseName, identity, purpose, username, password: secret, grants }; },
    async listIdentities(application) { const [rows] = await q('SELECT name, application_name AS application, purpose, database_name AS database, username, active, created_at FROM elera_meta.identities WHERE application_name = ' + literal(application) + ' ORDER BY name'); return rows; },
    async revokeIdentity(identity) { await q(`UPDATE elera_meta.identities SET active=FALSE WHERE name=${literal(identity)}`); return { identity, revoked: true }; },
    async rotateIdentity(identity) { name(identity, 'identity'); const secret = password(); const [rows] = await q(`SELECT username FROM elera_meta.identities WHERE name=${literal(identity)} AND active=TRUE`); const username = rows[0]?.username; if (!username) throw Object.assign(new Error('identity not found'), { statusCode: 404 }); await query(`ALTER USER ${literal(username)}@'%' IDENTIFIED BY ${literal(secret)}`); await query('FLUSH PRIVILEGES'); return { identity, username, password: secret, rotated: true }; },
    async issueToken({ tokenName, application, identity = null, scopes = [] }) { name(tokenName, 'token'); const secret = randomBytes(32).toString('base64url'); await q(`INSERT INTO elera_meta.scoped_tokens (name, token_hash, application_name, identity_name, scopes_json) VALUES (${literal(tokenName)}, ${literal(hash(secret))}, ${application ? literal(application) : 'NULL'}, ${identity ? literal(identity) : 'NULL'}, ${literal(JSON.stringify(scopes))}) ON DUPLICATE KEY UPDATE token_hash=VALUES(token_hash), active=TRUE, rotated_at=CURRENT_TIMESTAMP`); return { name: tokenName, token: secret, application, identity, scopes }; },
    async authenticate(token) { if (!token) return null; const [rows] = await q(`SELECT name, application_name AS application, identity_name AS identity, scopes_json FROM elera_meta.scoped_tokens WHERE token_hash=${literal(hash(token))} AND active=TRUE`); const row = rows[0]; return row ? { ...row, scopes: JSON.parse(row.scopes_json ?? '[]') } : null; }
  };
}
