import { createHash, randomBytes } from 'node:crypto';
import { generate as generateSnowflake } from '@eliware/snowflake';
import { identifier, literal } from '../accounts/sql.mjs';
import { createSecretBox } from './secret-box.mjs';
import { validateGrantPolicy } from '../accounts/grant-policy.mjs';
import { tokenMatchesHash } from './token-authentication.mjs';

const name = (value, label) => { if (typeof value !== 'string' || !/^[A-Za-z][A-Za-z0-9_-]{0,62}$/.test(value)) throw Object.assign(new Error(`${label} is invalid`), { statusCode: 400 }); return value; };
const fqdn = (value, label) => { if (typeof value !== 'string' || value.length > 253 || !value.includes('.') || !/^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)+$/i.test(value)) throw Object.assign(new Error(`${label} must be a fully qualified hostname`), { statusCode: 400 }); return value; };
const hash = (value) => createHash('sha256').update(value).digest('hex');
const password = () => randomBytes(24).toString('base64url');

export function createManagedMetadata({ query, identity, database = 'elera_meta', credentialKey = process.env.ELERA_CREDENTIAL_KEY } = {}) {
  if (typeof query !== 'function') throw new TypeError('query function is required');
  if (!/^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(database)) throw new TypeError('metadata database name is invalid');
  fqdn(identity?.name, 'runtime identity');
  const q = (sql, params) => query(sql.replaceAll('elera_meta', `\`${database}\``), params);
  const box = credentialKey ? createSecretBox(credentialKey) : null;
  const deleteOperations = new Map();
  return {
    async createDatabase({ application, databaseName }) { name(application, 'application'); name(databaseName, 'database'); const [existing] = await q(`SELECT database_id, physical_name FROM elera_meta.managed_databases WHERE name=${literal(databaseName)} AND application_name=${literal(application)}`); const databaseId = existing[0]?.database_id ?? String(generateSnowflake()); const physicalName = existing[0]?.physical_name ?? `elera_db_${databaseId}`; const applicationId = String(generateSnowflake()); await q(`INSERT INTO elera_meta.applications (application_id, name) VALUES (${literal(applicationId)}, ${literal(application)}) ON DUPLICATE KEY UPDATE name=name`); await q(`INSERT INTO elera_meta.managed_databases (database_id, name, physical_name, application_name) VALUES (${literal(databaseId)}, ${literal(databaseName)}, ${literal(physicalName)}, ${literal(application)}) ON DUPLICATE KEY UPDATE application_name=VALUES(application_name), physical_name=VALUES(physical_name)`); await query(`CREATE DATABASE IF NOT EXISTS ${identifier(physicalName)}`); return { databaseId, application, database: databaseName, physicalName }; },
    async listDatabases() { const [rows] = await q('SELECT database_id, name, application_name AS application, created_at FROM elera_meta.managed_databases ORDER BY name'); return rows; },
    async deleteDatabase({ databaseId, dryRun = false, confirm = false, idempotencyKey } = {}) { if (typeof databaseId !== 'string' || !databaseId) throw Object.assign(new Error('databaseId is required'), { statusCode: 400 }); if (idempotencyKey && deleteOperations.has(idempotencyKey)) return deleteOperations.get(idempotencyKey); const [rows] = await q(`SELECT database_id, name, physical_name, application_name AS application FROM elera_meta.managed_databases WHERE database_id=${literal(databaseId)}`); const database = rows[0]; if (!database) throw Object.assign(new Error('database not found'), { statusCode: 404 }); const result = { databaseId, application: database.application, database: database.name, changed: !dryRun && confirm, status: dryRun ? 'planned' : confirm ? 'completed' : 'rejected' }; if (!dryRun && !confirm) throw Object.assign(new Error('database deletion requires confirm: true'), { statusCode: 409 }); if (!dryRun) { await query(`DROP DATABASE IF EXISTS ${identifier(database.physical_name)}`); await q(`DELETE FROM elera_meta.managed_databases WHERE database_id=${literal(databaseId)}`); } if (idempotencyKey) deleteOperations.set(idempotencyKey, result); return result; },
    async createIdentity({ application, databaseName, identity, purpose = 'runtime', grants = [] }) { name(application, 'application'); name(databaseName, 'database'); name(identity, 'identity'); if (!['runtime', 'readonly', 'migration', 'reporting', 'admin'].includes(purpose)) throw Object.assign(new Error('identity purpose is invalid'), { statusCode: 400 }); if (!box) throw new Error('credential encryption is not configured'); const username = `${application}_${identity}`; const secret = password(); const identityId = String(generateSnowflake()); grants.forEach(validateGrantPolicy); const database = await this.createDatabase({ application, databaseName }); await q(`INSERT INTO elera_meta.identities (identity_id, name, application_name, purpose, database_name, username, credential_ciphertext) VALUES (${literal(identityId)}, ${literal(identity)}, ${literal(application)}, ${literal(purpose)}, ${literal(database.physicalName)}, ${literal(username)}, ${literal(box.seal(secret))}) ON DUPLICATE KEY UPDATE purpose=VALUES(purpose), database_name=VALUES(database_name), credential_ciphertext=VALUES(credential_ciphertext), active=TRUE`); await q(`INSERT INTO elera_meta.grants_policy (identity_name, application_name, grants_json) VALUES (${literal(identity)}, ${literal(application)}, ${literal(JSON.stringify(grants))}) ON DUPLICATE KEY UPDATE grants_json=VALUES(grants_json)`); await query(`CREATE USER IF NOT EXISTS ${literal(username)}@'%' IDENTIFIED BY ${literal(secret)}`); await query(`ALTER USER ${literal(username)}@'%' IDENTIFIED BY ${literal(secret)}`); await query(`REVOKE ALL PRIVILEGES, GRANT OPTION FROM ${literal(username)}@'%'`); for (const grant of grants) await query(`GRANT ${grant} ON ${identifier(database.physicalName)}.* TO ${literal(username)}@'%'`); await query('FLUSH PRIVILEGES'); return { application, database: databaseName, identity, purpose, username, password: secret, grants }; },
    async listIdentities(application) { const filter = application ? ` WHERE i.application_name = ${literal(application)}` : ''; const [rows] = await q(`SELECT i.name, i.application_name AS application, i.purpose, d.name AS database, i.username, i.active, i.created_at, g.grants_json FROM elera_meta.identities i JOIN elera_meta.managed_databases d ON d.physical_name=i.database_name AND d.application_name=i.application_name LEFT JOIN elera_meta.grants_policy g ON g.identity_name = i.name AND g.application_name = i.application_name${filter} ORDER BY i.name`); return rows.map(({ grants_json, ...row }) => ({ ...row, grants: Array.isArray(grants_json) ? grants_json : JSON.parse(grants_json ?? '[]') })); },
    async revokeIdentity(identity) { await q(`UPDATE elera_meta.identities SET active=FALSE WHERE name=${literal(identity)}`); return { identity, revoked: true }; },
    async rotateIdentity(identity) { name(identity, 'identity'); if (!box) throw new Error('credential encryption is not configured'); const secret = password(); const [rows] = await q(`SELECT username FROM elera_meta.identities WHERE name=${literal(identity)} AND active=TRUE`); const username = rows[0]?.username; if (!username) throw Object.assign(new Error('identity not found'), { statusCode: 404 }); await q(`UPDATE elera_meta.identities SET credential_ciphertext=${literal(box.seal(secret))} WHERE name=${literal(identity)}`); await query(`ALTER USER ${literal(username)}@'%' IDENTIFIED BY ${literal(secret)}`); await query('FLUSH PRIVILEGES'); return { identity, username, password: secret, rotated: true }; },
    async lease({ identity: credentialIdentity, routes = {}, nodeIdentity, ports }) { name(credentialIdentity, 'identity'); if (!box) throw new Error('credential encryption is not configured'); const runtimeNode = fqdn(identity?.name, 'runtime identity'); if (nodeIdentity !== undefined && nodeIdentity !== runtimeNode) throw Object.assign(new Error('requested node identity does not match runtime identity'), { statusCode: 409 }); const [rows] = await q(`SELECT i.application_name AS application, d.name AS database, d.physical_name AS physical_database, i.username, i.credential_ciphertext FROM elera_meta.identities i JOIN elera_meta.managed_databases d ON d.physical_name=i.database_name AND d.application_name=i.application_name WHERE i.name=${literal(credentialIdentity)} AND i.active=TRUE`); const row = rows[0]; if (!row) throw Object.assign(new Error('identity not found'), { statusCode: 404 }); const primary = routes.primary ?? [{ host: runtimeNode, port: 3306, nodeId: runtimeNode }]; for (const route of [...primary, ...(routes.balanced ?? primary)]) { fqdn(route?.host, 'lease route host'); fqdn(route?.nodeId, 'lease route node'); } return { application: row.application, database: row.database, physicalDatabase: row.physical_database, identity: credentialIdentity, username: row.username, password: box.open(row.credential_ciphertext), routes: { primary, balanced: routes.balanced ?? primary }, nodeIdentity: runtimeNode, ports, expiresAt: new Date(Date.now() + 3600000).toISOString() }; },
    async issueToken({ tokenName, application, identity, scopes = [] }) { name(tokenName, 'token'); name(application, 'application'); name(identity, 'identity'); const [rows] = await q(`SELECT i.application_name AS application, d.name AS database FROM elera_meta.identities i JOIN elera_meta.managed_databases d ON d.physical_name=i.database_name AND d.application_name=i.application_name WHERE i.name=${literal(identity)} AND i.active=TRUE`); const owner = rows[0]; if (!owner) throw Object.assign(new Error('identity not found'), { statusCode: 404 }); if (owner.application !== application) throw Object.assign(new Error('identity does not belong to application'), { statusCode: 400 }); const secret = randomBytes(32).toString('base64url'); const tokenId = String(generateSnowflake()); await q(`INSERT INTO elera_meta.scoped_tokens (name, token_hash, application_name, identity_name, scopes_json, token_id) VALUES (${literal(tokenName)}, ${literal(hash(secret))}, ${literal(application)}, ${literal(identity)}, ${literal(JSON.stringify(scopes))}, ${literal(tokenId)}) ON DUPLICATE KEY UPDATE token_hash=VALUES(token_hash), active=TRUE, rotated_at=CURRENT_TIMESTAMP`); return { name: tokenName, token: secret, application, database: owner.database, identity, scopes }; },
    async revokeToken({ tokenName, application } = {}) { name(tokenName, 'token'); name(application, 'application'); await q(`UPDATE elera_meta.scoped_tokens SET active=FALSE WHERE name=${literal(tokenName)} AND application_name=${literal(application)}`); return { name: tokenName, application, revoked: true }; },
    async authenticate(token) { if (!token) return null; const [rows] = await q('SELECT t.name, t.application_name AS application, d.name AS database, d.physical_name AS physical_database, t.identity_name AS identity, t.token_hash, t.scopes_json FROM elera_meta.scoped_tokens t LEFT JOIN elera_meta.identities i ON i.name=t.identity_name AND i.application_name=t.application_name LEFT JOIN elera_meta.managed_databases d ON d.physical_name=i.database_name AND d.application_name=i.application_name WHERE t.active=TRUE'); const row = rows.find((candidate) => tokenMatchesHash(token, candidate.token_hash)); if (!row) return null; const { token_hash: _tokenHash, scopes_json: scopesJson, physical_database: physicalDatabase, ...metadata } = row; return { ...metadata, ...(physicalDatabase ? { physicalDatabase } : {}), scopes: Array.isArray(scopesJson) ? scopesJson : JSON.parse(scopesJson ?? '[]') }; }
  };
}
