export const META_DATABASE = 'elera_meta';
export const META_SCHEMA = [
  "CREATE TABLE IF NOT EXISTS metadata (key_name VARCHAR(255) PRIMARY KEY, value_json JSON NOT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)",
  "CREATE TABLE IF NOT EXISTS applications (application_id VARCHAR(32) PRIMARY KEY, name VARCHAR(255) NOT NULL UNIQUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
  "CREATE TABLE IF NOT EXISTS managed_databases (database_id VARCHAR(32) PRIMARY KEY, name VARCHAR(255) NOT NULL UNIQUE, physical_name VARCHAR(255) NOT NULL UNIQUE, application_name VARCHAR(255) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_managed_databases_application (application_name))",
  "CREATE TABLE IF NOT EXISTS identities (identity_id VARCHAR(32) PRIMARY KEY, name VARCHAR(255) NOT NULL, application_name VARCHAR(255) NOT NULL, purpose VARCHAR(32) NOT NULL, database_name VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, host_pattern VARCHAR(255) NOT NULL DEFAULT '%', active BOOLEAN NOT NULL DEFAULT TRUE, credential_ciphertext TEXT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY identity_application_name (application_name, name), UNIQUE KEY identity_username (username, host_pattern), INDEX idx_identities_application (application_name))",
  "CREATE TABLE IF NOT EXISTS grants_policy (identity_name VARCHAR(255) NOT NULL, application_name VARCHAR(255) NOT NULL, grants_json JSON NOT NULL, PRIMARY KEY (application_name, identity_name), updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)",
  "CREATE TABLE IF NOT EXISTS scoped_tokens (token_id VARCHAR(32) PRIMARY KEY, name VARCHAR(255) NOT NULL, token_hash CHAR(64) NOT NULL, application_name VARCHAR(255) NOT NULL, identity_name VARCHAR(255) NULL, scopes_json JSON NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, rotated_at TIMESTAMP NULL, UNIQUE KEY scoped_token_application_name (application_name, name))",
  "CREATE TABLE IF NOT EXISTS artifacts (name VARCHAR(255) PRIMARY KEY, kind VARCHAR(64) NOT NULL, ciphertext LONGTEXT NOT NULL, key_version VARCHAR(128) NOT NULL, checksum CHAR(64) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)",
  "CREATE TABLE IF NOT EXISTS routing_assignments (application_name VARCHAR(255) PRIMARY KEY, writer_host VARCHAR(255) NOT NULL, bundle_version VARCHAR(128) NOT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)",
];
