import { expect, jest, test } from '@jest/globals';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const createControlApi = jest.fn((options) => ({ options }));
jest.unstable_mockModule('../../src/control-api.mjs', () => ({ createControlApi }));
const { createSupervisorControlComposition } = await import('../../src/runtime/control-composition.mjs');

test('composes the control API with cluster and runtime dependencies', async () => {
  const dataDir = await mkdtemp(join(tmpdir(), 'supervisor-reset-'));
  const query = jest.fn();
  const stop = jest.fn();
  const observationStore = { all: jest.fn().mockImplementationOnce(() => [{ nodeId: 'donor', synced: true, primary: 'Primary', health: 'ok' }]).mockImplementation(() => [{ node: 'donor', healthy: true, primary: true }]) };
  const result = createSupervisorControlComposition({ db: { query }, metadata: {}, managed: {}, applications: {}, reconciler: {}, artifactStore: {}, routingBundles: { lease: jest.fn() }, routingEvent: jest.fn(), recovery: { status: jest.fn(() => ({})) }, observationStore, health: { status: jest.fn(async () => ({ ready: false })), cacheInfo: jest.fn(() => ({})) }, clusterDrain: { set: jest.fn() }, lifecycle: { get: jest.fn() }, telemetry: { summary: jest.fn(), details: jest.fn() }, config: { elera: true, runtimeNodeName: 'supervisor', dataDir }, intentState: {}, coldState: { drain: { isDraining: jest.fn(() => false), active: jest.fn(() => 0) }, clusterDrain: { set: jest.fn() } }, processController: { stop, start: jest.fn() }, applyIntent: jest.fn(), environment: {}, log: {} });
  expect(result).toBeDefined();
  const options = result.options;
  expect(options.getConfig()).toEqual(expect.objectContaining({ elera: true, runtimeNodeName: 'supervisor', dataDir }));
  await options.getStatus();
  options.getTraffic();
  options.getTelemetry();
  options.getTelemetryDetails('app');
  options.setDrain(true, false);
  options.getActiveIntent();
  options.getActiveIntent.apply({});
  options.leaseCredentials({});
  options.getColdBootstrap();
  options.getColdEvidence();
  options.getColdRecoveryProtocol();
  options.getColdBootstrapLocal();
  await expect(options.nodeDataReset.reset({ node: 'supervisor', dataDir, confirmation: 'RESET supervisor', dryRun: true })).resolves.toMatchObject({ status: 'planned' });
  await expect(options.nodeDataReset.reset({ node: 'supervisor', dataDir, confirmation: 'RESET supervisor', dryRun: true, force: true, fenced: true, routingExcluded: true, recoveryDisposition: 'single-member-resync' })).resolves.toMatchObject({ status: 'planned' });
  await expect(options.nodeDataReset.reset({ node: 'supervisor', dataDir, confirmation: 'RESET supervisor', dryRun: false, idempotencyKey: 'composition-reset' })).resolves.toMatchObject({ status: 'completed' });
  expect(stop).toHaveBeenCalled();
  options.bootstrap();
  await options.db.query('SELECT 1');
  await options.lifecycle.plan('bootstrap');
  await options.lifecycle.execute('bootstrap', { confirm: true });
  expect(query).toHaveBeenCalled();
  await rm(dataDir, { recursive: true, force: true });
});
