import { expect, jest, test } from '@jest/globals';
import { createSupervisorIntentApplication } from '../../src/runtime/intent-application.mjs';

const setup = (change) => { const processController = { child: { kill: jest.fn() }, stop: jest.fn(), start: jest.fn() }; const intentState = { read: jest.fn(async () => ({ active: true })), apply: jest.fn(async () => ({ applied: true })) }; const setRestarting = jest.fn(); const apply = createSupervisorIntentApplication({ intentState, processController, args: ['--x'], config: { timeoutMs: 10 }, plan: () => ({ change, reason: 'unsafe' }), setRestarting }); return { apply, processController, intentState, setRestarting }; };
test('rejects unsafe changes without applying them', async () => { const value = setup('unsafe'); await expect(value.apply({})).rejects.toMatchObject({ code: 'UNSAFE_INTENT_CHANGE' }); expect(value.intentState.apply).not.toHaveBeenCalled(); });
test('applies reload changes and signals MariaDB', async () => { const value = setup('reload'); await expect(value.apply({})).resolves.toEqual({ applied: true }); expect(value.processController.child.kill).toHaveBeenCalledWith('SIGHUP'); });
test('restarts MariaDB and clears restart state even on success', async () => { const value = setup('restart'); await value.apply({}); expect(value.setRestarting).toHaveBeenNthCalledWith(1, true); expect(value.processController.start).toHaveBeenCalledWith(['--x']); expect(value.setRestarting).toHaveBeenLastCalledWith(false); });
test('clears restart state when restart fails', async () => { const value = setup('restart'); value.processController.stop.mockRejectedValue(new Error('stop failed')); await expect(value.apply({})).rejects.toThrow('stop failed'); expect(value.setRestarting).toHaveBeenLastCalledWith(false); });
test('loads environment intent when no persisted intent exists', async () => { const value = setup('none'); value.intentState.read.mockResolvedValue(null); const load = jest.fn(() => ({ active: true })); const apply = createSupervisorIntentApplication({ intentState: value.intentState, processController: value.processController, args: [], config: { timeoutMs: 1 }, load, plan: () => ({ change: 'none' }), setRestarting: jest.fn() }); await apply({ desired: true }); expect(load).toHaveBeenCalled(); });
