import { expect, jest, test } from '@jest/globals';
import { startSupervisorMariaDb } from '../../src/runtime/maria-startup.mjs';

const base = () => ({ config: { elera: true, startupTimeoutMs: 10, shutdownTimeoutMs: 10 }, startupDecision: { mode: 'join', reason: 'join', epoch: 1 }, processController: { start: jest.fn(() => Promise.resolve()), stop: jest.fn() }, recoveryState: { set: jest.fn() }, recoveryAudit: { joinStart: jest.fn(), failure: jest.fn() }, recoveryCompletion: {}, identity: { name: 'node-a' }, log: { warn: jest.fn(), error: jest.fn() }, signals: { shutdown: jest.fn() } });

test('refuses MariaDB start without recovery authority', () => { const value = base(); startSupervisorMariaDb({ ...value, shouldStart: () => false }); expect(value.processController.start).not.toHaveBeenCalled(); expect(value.log.warn).toHaveBeenCalled(); });
test('starts a joining member and records the transition', async () => { const value = base(); startSupervisorMariaDb({ ...value, shouldStart: () => true }); await Promise.resolve(); expect(value.recoveryState.set).toHaveBeenCalledWith('joining', { reason: 'join' }); expect(value.recoveryAudit.joinStart).toHaveBeenCalled(); });
test('handles bootstrap watch timeout and completion', async () => { let watchOptions; const value = { ...base(), startupDecision: { mode: 'bootstrap', localWinner: true, epoch: 2, recoveryEpoch: { clusterId: 'c', quorum: ['a'] } }, recoveryCompletion: { publish: jest.fn() }, startupServer: { close: jest.fn() }, coldRecoveryProtocol: { complete: jest.fn() }, createWatch: jest.fn((options) => { watchOptions = options; options.onTimeout(); return async () => ({ ready: true }); }) }; startSupervisorMariaDb({ ...value, shouldStart: () => true }); await new Promise((resolve) => setImmediate(resolve)); expect(watchOptions.isReady({ values: { wsrep_local_state_comment: 'Synced', wsrep_ready: 'ON', wsrep_cluster_status: 'Primary' } })).toBe(true); expect(watchOptions.isReady({ values: {} })).toBe(false); expect(value.recoveryAudit.failure).toHaveBeenCalled(); expect(value.coldRecoveryProtocol.complete).toHaveBeenCalled(); expect(value.recoveryState.set).toHaveBeenCalledWith('complete', expect.any(Object)); });
test('ignores an unsuccessful bootstrap watch and reports process-start failure', async () => { const value = { ...base(), startupDecision: { mode: 'bootstrap', localWinner: true }, processController: { start: jest.fn(() => Promise.resolve()), stop: jest.fn() }, createWatch: jest.fn(() => async () => ({ ready: false })) }; startSupervisorMariaDb({ ...value, shouldStart: () => true }); await new Promise((resolve) => setImmediate(resolve)); expect(value.recoveryState.set).not.toHaveBeenCalledWith('complete', expect.anything()); const failed = { ...base(), processController: { start: jest.fn(() => Promise.reject(new Error('no start'))) } }; startSupervisorMariaDb({ ...failed, shouldStart: () => true }); await new Promise((resolve) => setImmediate(resolve)); expect(failed.log.error).toHaveBeenCalled(); expect(failed.signals.shutdown).toHaveBeenCalledWith('mariadbd-error'); });
