import { expect, jest, test } from '@jest/globals';
import { startSupervisorMariaDb } from '../../src/runtime/maria-startup.mjs';

const base = () => ({ config: { elera: true, clusterSize: 1, startupTimeoutMs: 10, shutdownTimeoutMs: 10 }, startupDecision: { mode: 'join', reason: 'join', epoch: 1 }, health: { status: jest.fn(async () => ({ values: { wsrep_local_state_comment: 'Synced', wsrep_ready: 'ON', wsrep_cluster_status: 'Primary', wsrep_cluster_size: '1' } })) }, processController: { start: jest.fn(() => Promise.resolve()), stop: jest.fn() }, recoveryState: { set: jest.fn() }, recoveryAudit: { joinStart: jest.fn(), failure: jest.fn() }, recoveryCompletion: {}, identity: { name: 'node-a' }, log: { warn: jest.fn(), error: jest.fn() }, signals: { shutdown: jest.fn() } });

test('refuses MariaDB start without recovery authority', () => { const value = base(); startSupervisorMariaDb({ ...value, shouldStart: () => false }); expect(value.processController.start).not.toHaveBeenCalled(); expect(value.log.warn).toHaveBeenCalled(); });
test('starts explicitly authorized local bootstrap', () => { const value = { ...base(), startupDecision: { mode: 'bootstrap', localWinner: true }, processController: { start: jest.fn(() => Promise.resolve()), stop: jest.fn() } }; startSupervisorMariaDb(value); expect(value.processController.start).toHaveBeenCalled(); });
test('starts an explicitly authorized join', () => { const value = { ...base(), startupDecision: { mode: 'join', bootstrapComplete: true }, processController: { start: jest.fn(() => Promise.resolve()), stop: jest.fn() } }; startSupervisorMariaDb(value); expect(value.processController.start).toHaveBeenCalled(); });
test('completes an explicit join after expected membership is ready', async () => { const value = { ...base(), config: { ...base().config, clusterSize: 3 }, startupDecision: { mode: 'join', bootstrapComplete: true, reason: 'explicit join initialization handoff' }, createWatch: jest.fn((options) => { expect(options.isReady({ values: { wsrep_local_state_comment: 'Synced', wsrep_ready: 'ON', wsrep_cluster_status: 'Primary', wsrep_cluster_size: '3' } })).toBe(true); return async () => ({ ready: true }); }), processController: { start: jest.fn(() => Promise.resolve()), stop: jest.fn() } }; startSupervisorMariaDb(value); await new Promise((resolve) => setImmediate(resolve)); expect(value.recoveryState.set).toHaveBeenCalledWith('complete', expect.objectContaining({ reason: expect.stringContaining('join completed') })); });
test('leaves join state pending when readiness times out', async () => { const value = { ...base(), startupDecision: { mode: 'join', bootstrapComplete: true }, createWatch: jest.fn(() => async () => ({ ready: false })) }; startSupervisorMariaDb(value); await new Promise((resolve) => setImmediate(resolve)); expect(value.recoveryState.set).toHaveBeenCalledWith('joining', expect.any(Object)); expect(value.recoveryState.set).not.toHaveBeenCalledWith('complete', expect.anything()); });
test('uses configured cluster size for explicit bootstrap readiness', async () => { let watchOptions; const value = { ...base(), config: { ...base().config, clusterSize: 3 }, startupDecision: { mode: 'bootstrap', localWinner: true, epoch: null }, recoveryCompletion: { publish: jest.fn() }, coldRecoveryProtocol: { complete: jest.fn() }, createWatch: jest.fn((options) => { watchOptions = options; return async () => ({ ready: true }); }), processController: { start: jest.fn(() => Promise.resolve()), stop: jest.fn() } }; startSupervisorMariaDb(value); await new Promise((resolve) => setImmediate(resolve)); expect(watchOptions.isReady({ values: { wsrep_local_state_comment: 'Synced', wsrep_ready: 'ON', wsrep_cluster_status: 'Primary', wsrep_cluster_size: '3' } })).toBe(true); });
test('completes explicit bootstrap locally after expected membership is ready', async () => { const value = { ...base(), config: { ...base().config, clusterSize: 3 }, startupDecision: { mode: 'bootstrap', localWinner: true, epoch: null }, coldRecoveryProtocol: { complete: jest.fn() }, createWatch: jest.fn(() => async () => ({ ready: true })) }; startSupervisorMariaDb(value); await new Promise((resolve) => setImmediate(resolve)); expect(value.coldRecoveryProtocol.complete).not.toHaveBeenCalled(); expect(value.recoveryState.set).toHaveBeenCalledWith('complete', expect.objectContaining({ reason: expect.stringContaining('explicit bootstrap') })); });
test('starts a joining member and records the transition', async () => { const value = base(); startSupervisorMariaDb({ ...value, shouldStart: () => true }); await Promise.resolve(); expect(value.recoveryState.set).toHaveBeenCalledWith('joining', { reason: 'join' }); expect(value.recoveryAudit.joinStart).toHaveBeenCalled(); });
test('handles bootstrap watch timeout and completion', async () => { let watchOptions; const value = { ...base(), startupDecision: { mode: 'bootstrap', localWinner: true, epoch: 2, recoveryEpoch: { clusterId: 'c', quorum: ['a'] } }, recoveryCompletion: { publish: jest.fn() }, startupServer: { close: jest.fn() }, coldRecoveryProtocol: { complete: jest.fn() }, createWatch: jest.fn((options) => { watchOptions = options; options.onTimeout(); return async () => ({ ready: true }); }) }; startSupervisorMariaDb({ ...value, shouldStart: () => true }); await new Promise((resolve) => setImmediate(resolve)); expect(watchOptions.isReady({ values: { wsrep_local_state_comment: 'Synced', wsrep_ready: 'ON', wsrep_cluster_status: 'Primary', wsrep_cluster_size: '1' } })).toBe(true); expect(watchOptions.isReady({ values: { wsrep_local_state_comment: 'Synced', wsrep_ready: 'ON', wsrep_cluster_status: 'Primary', wsrep_cluster_size: '0' } })).toBe(false); expect(value.recoveryAudit.failure).toHaveBeenCalled(); expect(value.coldRecoveryProtocol.complete).toHaveBeenCalled(); expect(value.recoveryState.set).toHaveBeenCalledWith('complete', expect.any(Object)); });
test('ignores an unsuccessful bootstrap watch and reports process-start failure', async () => { const value = { ...base(), startupDecision: { mode: 'bootstrap', localWinner: true }, processController: { start: jest.fn(() => Promise.resolve()), stop: jest.fn() }, createWatch: jest.fn(() => async () => ({ ready: false })) }; startSupervisorMariaDb({ ...value, shouldStart: () => true }); await new Promise((resolve) => setImmediate(resolve)); expect(value.recoveryState.set).not.toHaveBeenCalledWith('complete', expect.anything()); const failed = { ...base(), processController: { start: jest.fn(() => Promise.reject(new Error('no start'))) } }; startSupervisorMariaDb({ ...failed, shouldStart: () => true }); await new Promise((resolve) => setImmediate(resolve)); expect(failed.log.error).toHaveBeenCalled(); expect(failed.signals.shutdown).toHaveBeenCalledWith('mariadbd-error'); });
