import { expect, jest, test } from '@jest/globals';
import { authorizeSupervisorRecovery } from '../../src/runtime/recovery-authorization.mjs';

const base = (fetchImpl) => ({ decision: { mode: 'bootstrap', localWinner: true, winner: 'a', epoch: 3, reason: 'winner' }, members: [{ name: 'a', local: true, url: 'http://a' }, { name: 'b', url: 'http://b' }, { name: 'c', url: 'http://c' }], config: { httpPort: 8080, timeoutMs: 10, dataDir: '/data' }, intentState: { paths: { renderedPath: '/state.cnf' } }, recoveryProtocol: { authorize: jest.fn(), beginBootstrap: jest.fn() }, recoveryState: { set: jest.fn() }, recoveryAudit: { lease: jest.fn(), authorization: jest.fn(), bootstrapStart: jest.fn() }, log: { warn: jest.fn() }, environment: { ROOT_TOKEN: 'root' }, fetchImpl, promote: jest.fn(), argumentsFor: jest.fn(() => ['--x']), applyArguments: jest.fn((args) => [...args, '--bootstrap']) });

test('authorizes winner after lease quorum and builds bootstrap args', async () => { const value = base(async () => ({ ok: true, json: async () => ({ data: { granted: true } }) })); const promote = jest.fn(); await expect(authorizeSupervisorRecovery({ ...value, pathExists: jest.fn().mockResolvedValue(undefined), promote })).resolves.toMatchObject({ args: ['--x', '--bootstrap'] }); expect(promote).toHaveBeenCalledWith('/data/grastate.dat'); expect(value.recoveryProtocol.authorize).toHaveBeenCalled(); expect(value.recoveryState.set).toHaveBeenCalledWith('recovery-authorized', expect.any(Object)); });
test('allows a fresh explicit bootstrap without grastate.dat', async () => { const value = base(async () => ({ ok: true, json: async () => ({ data: { granted: true } }) })); const pathExists = jest.fn().mockRejectedValue(Object.assign(new Error('missing'), { code: 'ENOENT' })); await expect(authorizeSupervisorRecovery({ ...value, pathExists })).resolves.toMatchObject({ args: ['--x', '--bootstrap'] }); expect(value.log.warn).not.toHaveBeenCalled(); });
test('fails closed for non-missing state-file errors', async () => { const value = base(async () => ({ ok: true, json: async () => ({ data: { granted: true } }) })); await expect(authorizeSupervisorRecovery({ ...value, pathExists: jest.fn().mockRejectedValue(new Error('permission denied')) })).rejects.toThrow('permission denied'); });
test('blocks winner when lease quorum is unavailable', async () => { const value = base(async () => ({ ok: false })); await expect(authorizeSupervisorRecovery(value)).resolves.toMatchObject({ decision: { mode: 'blocked' } }); expect(value.recoveryState.set).toHaveBeenCalledWith('blocked-ambiguous', expect.any(Object)); });
test('records a failed lease request as a denied claim', async () => { const value = base(async () => { throw new Error('peer unavailable'); }); await expect(authorizeSupervisorRecovery(value)).resolves.toMatchObject({ decision: { mode: 'blocked' } }); expect(value.recoveryAudit.lease).toHaveBeenCalledWith(expect.objectContaining({ granted: false })); });
test('does nothing for non-winner decisions', async () => { const value = base(jest.fn()); value.decision = { mode: 'join', localWinner: false }; await expect(authorizeSupervisorRecovery(value)).resolves.toEqual({ decision: value.decision, args: undefined }); expect(value.fetchImpl).not.toHaveBeenCalled(); });
