import { expect, jest, test } from '@jest/globals';
import { resolveExplicitSupervisorStartup } from '../../src/runtime/startup-decision-wiring.mjs';
test('returns unchanged args without explicit decision', async () => { const args = ['--x']; await expect(resolveExplicitSupervisorStartup({ environment: {}, nodeName: 'node', args, decision: () => undefined })).resolves.toEqual({ explicit: false, decision: undefined, args }); });
test('preserves explicit non-bootstrap decisions', async () => { const decision = { mode: 'join', reason: 'operator' }; await expect(resolveExplicitSupervisorStartup({ environment: {}, nodeName: 'node', args: [], decision: () => decision })).resolves.toEqual({ explicit: true, decision, args: [] }); });
test('passes the configured bootstrap address to explicit joins', async () => { const addArguments = jest.fn((args, decision, options) => [decision.mode, options.joinAddress]); const decision = { mode: 'join', reason: 'operator' }; await expect(resolveExplicitSupervisorStartup({ environment: {}, nodeName: 'node', args: [], joinAddress: 'elera-0', decision: () => decision, addArguments })).resolves.toEqual({ explicit: true, decision, args: ['join', 'elera-0'] }); });
test('preserves explicit standalone arguments without startup rewriting', async () => { const decision = { mode: 'standalone', reason: 'operator' }; await expect(resolveExplicitSupervisorStartup({ environment: {}, nodeName: 'node', args: ['--x'], decision: () => decision })).resolves.toEqual({ explicit: true, decision, args: ['--x'] }); });
test('promotes and adds bootstrap arguments', async () => { const promote = jest.fn(); const addArguments = jest.fn(() => ['--bootstrap']); const decision = { mode: 'bootstrap', epoch: 2 }; await expect(resolveExplicitSupervisorStartup({ environment: {}, nodeName: 'node', dataDir: '/data', args: [], decision: () => decision, pathExists: jest.fn().mockResolvedValue(undefined), promote, addArguments })).resolves.toEqual({ explicit: true, decision, args: ['--bootstrap'] }); expect(promote).toHaveBeenCalledWith('/data/grastate.dat'); });
test('allows fresh explicit bootstrap when state file is absent', async () => { const promote = jest.fn(); const addArguments = jest.fn(() => ['--bootstrap']); const decision = { mode: 'bootstrap', epoch: 2 }; await expect(resolveExplicitSupervisorStartup({ environment: {}, nodeName: 'node', dataDir: '/data', args: [], decision: () => decision, pathExists: jest.fn().mockRejectedValue(Object.assign(new Error('missing'), { code: 'ENOENT' })), promote, addArguments })).resolves.toEqual({ explicit: true, decision, args: ['--bootstrap'] }); expect(promote).not.toHaveBeenCalled(); });
test('fails closed for non-missing state errors', async () => { const decision = { mode: 'bootstrap', epoch: 2 }; await expect(resolveExplicitSupervisorStartup({ environment: {}, nodeName: 'node', dataDir: '/data', args: [], decision: () => decision, pathExists: jest.fn().mockRejectedValue(new Error('permission denied')) })).rejects.toThrow('permission denied'); });
