import { expect, test } from '@jest/globals';
import { createRoutingEventSnapshot } from '../../src/routing/event-snapshot.mjs';
import { validateRoutingEvent } from '@eliware/elera-lib';

test('creates stable versioned routing events and advances on changes', () => {
  const node = { nodeId: 'n', address: 'db', sqlPort: 3306, synced: true, primary: 'Primary', health: 'ok', observedAt: Date.now() };
  const observations = [node]; const snapshot = createRoutingEventSnapshot({ observationStore: { snapshot: () => observations }, environment: { ELERA_CLUSTER_SIZE: '1' } });
  const first = snapshot('app'); expect(first.type).toBe('routing.topology'); expect(first.topology.nodes[0].address).toBe('db'); expect(validateRoutingEvent(first)).toBe(first); expect(snapshot('app')).toBe(first);
  observations[0] = { ...node, drain: true }; expect(snapshot('app').version).toBe(2);
});
test('uses the last healthy topology during a temporary quorum loss and expires it', () => { let now = 1000; let observations = [{ nodeId: 'n', clusterId: 'c', address: 'db', sqlPort: 3306, synced: true, primary: 'Primary', health: 'ok', observedAt: now }]; const snapshot = createRoutingEventSnapshot({ observationStore: { snapshot: () => observations }, environment: { ELERA_CLUSTER_SIZE: '1' }, now: () => now }); const first = snapshot('app'); observations = [{ ...observations[0], synced: false, health: 'not-ready' }]; now += 1000; expect(snapshot('app').topology.nodes).toEqual(first.topology.nodes); now += 5000; expect(snapshot('app').topology.nodes[0].state).toBe('unready'); });
test('handles missing observations and applications without prior healthy routes', () => { const snapshot = createRoutingEventSnapshot({}); expect(snapshot()).toBeTruthy(); });
test('marks the local node immediately while draining', () => { const observationStore = { snapshot: () => [{ nodeId: 'elera', synced: true, primary: 'Primary', health: 'ok', address: 'db', sqlPort: 3306, observedAt: Date.now() }] }; const snapshot = createRoutingEventSnapshot({ observationStore, environment: { ELERA_NODE_NAME: 'elera', ELERA_CLUSTER_SIZE: '1' }, getDrained: () => true }); expect(snapshot('app').topology.nodes[0].draining).toBe(true); });
test('uses the resolved runtime identity when applying local drain state', () => { const now = Date.now(); const snapshot = createRoutingEventSnapshot({ observationStore: { snapshot: () => [{ nodeId: 'resolved.example', synced: true, primary: 'Primary', health: 'ok', address: 'db', sqlPort: 3306, observedAt: now }] }, nodeIdentity: { name: 'resolved.example' }, environment: { ELERA_CLUSTER_SIZE: '1' }, getDrained: () => true, now: () => now }); expect(snapshot('app').topology.nodes[0].draining).toBe(true); });
test('defaults the local drain state to serving', () => { const snapshot = createRoutingEventSnapshot({ observationStore: { snapshot: () => [{ nodeId: 'elera', synced: true, primary: 'Primary', health: 'ok', address: 'db', sqlPort: 3306, observedAt: Date.now() }] }, environment: { ELERA_CLUSTER_SIZE: '1' } }); expect(snapshot('app').topology.nodes[0].draining).toBe(false); });
test('does not surface assignment persistence failures', async () => { const snapshot = createRoutingEventSnapshot({ observationStore: { snapshot: () => [{ nodeId: 'n', synced: true, primary: 'Primary', health: 'ok', address: 'db', sqlPort: 3306, observedAt: Date.now() }] }, assignmentStore: { peek: () => undefined, set: async () => { throw new Error('storage unavailable'); } }, environment: { ELERA_CLUSTER_SIZE: '1' } }); expect(snapshot('app')).toBeTruthy(); await new Promise((resolve) => setImmediate(resolve)); });
