import { expect, jest, test } from '@jest/globals';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { createNodeDataReset } from '../../src/lifecycle/node-data-reset.mjs';

const base = (overrides = {}) => ({ node: 'node-a', dataDir: 'C:/data', getStatus: async () => ({ ready: false, values: { wsrep_local_state_comment: 'Initialized', wsrep_cluster_status: 'non-Primary' } }), ...overrides });
test('validates required reset dependencies and request types', async () => { expect(() => createNodeDataReset()).toThrow('required'); const service = createNodeDataReset(base()); await expect(service.reset({ node: 'node-a', confirmation: 'RESET node-a' })).rejects.toThrow('data directory'); await expect(service.reset({ node: 'node-a', dataDir: 'C:/data', confirmation: 'RESET node-a', dryRun: 'yes' })).rejects.toThrow('dryRun'); });
test('uses the default removal implementation for a disposable data directory', async () => { const directory = await mkdtemp(join(process.cwd(), 'reset-test-')); try { await mkdir(join(directory, 'mysql')); await writeFile(join(directory, 'mysql', 'state'), 'x'); const service = createNodeDataReset(base({ dataDir: directory, getStatus: async () => ({ ready: false, values: { wsrep_cluster_status: 'non-Primary' } }), getRecoveryState: () => null })); await service.reset({ node: 'node-a', dataDir: directory, confirmation: 'RESET node-a', dryRun: false, idempotencyKey: 'default-reset' }); await expect(import('node:fs/promises').then(({ access }) => access(join(directory, 'mysql')))).rejects.toBeTruthy(); } finally { await rm(directory, { recursive: true, force: true }); } });
test('plans reset without stopping or removing data', async () => { const stop = jest.fn(); const remove = jest.fn(); const result = await createNodeDataReset(base({ stop, remove })).reset({ node: 'node-a', dataDir: 'C:/data', dryRun: true, force: true, recoveryDisposition: 'reset-initialized-data', confirmation: 'RESET node-a' }); expect(result.status).toBe('planned'); expect(stop).not.toHaveBeenCalled(); expect(remove).not.toHaveBeenCalled(); });
test('executes confirmed initialized reset and replays idempotently', async () => { const stop = jest.fn(); const remove = jest.fn(); const audit = { reset: jest.fn() }; const service = createNodeDataReset(base({ stop, remove, audit })); const request = { node: 'node-a', dataDir: 'C:/data', dryRun: false, force: true, recoveryDisposition: 'reset-initialized-data', confirmation: 'RESET node-a', idempotencyKey: 'reset-1' }; await expect(service.reset(request)).resolves.toMatchObject({ status: 'completed', initialized: true }); await expect(service.reset(request)).resolves.toMatchObject({ status: 'completed' }); expect(stop).toHaveBeenCalledTimes(1); expect(remove).toHaveBeenCalledTimes(1); expect(audit.reset).toHaveBeenCalledTimes(1); });
test('executes a reset for an already fenced empty node', async () => { const service = createNodeDataReset(base({ getStatus: async () => ({ ready: false, values: {} }), stop: jest.fn(), remove: jest.fn() })); await expect(service.reset({ node: 'node-a', dataDir: 'C:/data', confirmation: 'RESET node-a', idempotencyKey: 'empty-reset' })).resolves.toMatchObject({ initialized: false }); });
test('supports fenced single-member resync only with a healthy Primary donor', async () => { const remove = jest.fn(); const service = createNodeDataReset(base({ getDonors: async () => [{ node: 'node-b', healthy: true, primary: true }], remove })); await expect(service.reset({ node: 'node-a', dataDir: 'C:/data', force: true, fenced: true, routingExcluded: true, recoveryDisposition: 'single-member-resync', confirmation: 'RESET node-a', idempotencyKey: 'resync-1' })).resolves.toMatchObject({ recoveryDisposition: 'single-member-resync', next: 'rejoin-and-receive-sst' }); expect(remove).toHaveBeenCalled(); });
test('permits explicit offline resync only with an attested donor', async () => { const service = createNodeDataReset(base({ getStatus: async () => { throw new Error('socket unavailable'); }, offlineRecovery: true, getDonors: async () => [] })); await expect(service.reset({ node: 'node-a', dataDir: 'C:/data', dryRun: true, force: true, offline: true, fenced: true, routingExcluded: true, donor: { node: 'node-b', healthy: true, primary: true }, recoveryDisposition: 'single-member-resync', confirmation: 'RESET node-a' })).resolves.toMatchObject({ next: 'rejoin-and-receive-sst' }); });
test('fails closed when SQL is unavailable without explicit offline recovery', async () => { const service = createNodeDataReset(base({ getStatus: async () => { throw new Error('socket unavailable'); } })); await expect(service.reset({ node: 'node-a', dataDir: 'C:/data', dryRun: true, confirmation: 'RESET node-a' })).rejects.toThrow('socket unavailable'); });
test('rejects resync without donor, fencing, or when node is live', async () => { const request = { node: 'node-a', dataDir: 'C:/data', force: true, fenced: true, routingExcluded: true, recoveryDisposition: 'single-member-resync', confirmation: 'RESET node-a', idempotencyKey: 'bad-resync' }; await expect(createNodeDataReset(base()).reset(request)).rejects.toThrow('healthy Primary donor'); await expect(createNodeDataReset(base({ getDonors: async () => [{ node: 'node-b', healthy: true, primary: true }] })).reset({ ...request, fenced: false })).rejects.toThrow('fenced'); await expect(createNodeDataReset(base({ getDonors: async () => [{ node: 'node-b', healthy: true, primary: true }], getStatus: async () => ({ ready: true }) })).reset(request)).rejects.toThrow('healthy'); });
test('fails closed for identity, path, confirmation, readiness, quorum, and initialized-data guards', async () => { const service = createNodeDataReset(base()); for (const request of [{ node: 'other', dataDir: 'C:/data', confirmation: 'RESET node-a' }, { node: 'node-a', dataDir: 'C:/other', confirmation: 'RESET node-a' }, { node: 'node-a', dataDir: 'C:/data', confirmation: 'wrong' }, { node: 'node-a', dataDir: 'C:/data', confirmation: 'RESET node-a' }, { node: 'node-a', dataDir: 'C:/data', confirmation: 'RESET node-a', force: true, idempotencyKey: 'missing-disposition' }]) await expect(service.reset(request)).rejects.toBeTruthy(); await expect(createNodeDataReset(base({ getStatus: async () => ({ ready: true }) })).reset({ node: 'node-a', dataDir: 'C:/data', confirmation: 'RESET node-a', idempotencyKey: 'ready' })).rejects.toThrow('healthy'); await expect(createNodeDataReset(base({ getRecoveryState: () => ({ state: 'blocked-ambiguous' }) })).reset({ node: 'node-a', dataDir: 'C:/data', confirmation: 'RESET node-a', idempotencyKey: 'ambiguous' })).rejects.toThrow('ambiguous'); });
