import { selectCandidate } from '../../../src/cluster/cold-bootstrap/candidate.mjs';
const node = (node, seqno, safeToBootstrap = false) => ({ node, uuid: 'cluster', seqno, safeToBootstrap });
test('selects the sole safe node even when another report has a higher seqno', () => expect(selectCandidate([node('a', 10, true), node('b', 11)])).toMatchObject({ eligible: true, candidate: { node: 'a' } }));
test('selects the unique highest seqno when none is marked safe', () => expect(selectCandidate([node('a', 10), node('b', 12)])).toMatchObject({ eligible: true, candidate: { node: 'b' } }));
test('selects a deterministic winner for an equivalent same-cluster position', () => expect(selectCandidate([node('b', 10), node('a', 10)])).toMatchObject({ eligible: true, candidate: { node: 'a' }, reason: expect.stringContaining('deterministic') }));
test('rejects UUID mismatch', () => expect(selectCandidate([node('a', 10), { ...node('b', 9), uuid: 'other' }]).reason).toContain('UUID'));
test('rejects empty evidence and multiple safe nodes', () => { expect(() => selectCandidate([])).toThrow('no Galera state'); expect(selectCandidate([node('a', 1, true), node('b', 1, true)]).reason).toContain('multiple'); });
test('rejects an unrecoverable all-negative state set', () => expect(selectCandidate([node('a', -1), node('b', -1)]).reason).toContain('recoverable'));
test('rejects non-array and incomplete candidate input', () => { expect(() => selectCandidate(undefined)).toThrow('no Galera state'); expect(selectCandidate([{ node: 'a', uuid: 'cluster', seqno: 1 }, { node: 'b', uuid: 'cluster', seqno: undefined }]).reason).toContain('incomplete'); });
test('rejects null and nameless evidence', () => { expect(selectCandidate([null]).reason).toContain('incomplete'); expect(selectCandidate([{ uuid: 'cluster', seqno: 1 }]).reason).toContain('incomplete'); });
