import { expect, jest, test } from '@jest/globals';
import { createColdBootstrapService } from '../../../src/cluster/cold-bootstrap/service.mjs';
import { handleClusterRoute } from '../../../src/api/routes/cluster.mjs';
test('requires configured cluster dependencies', () => {
  expect(() => createColdBootstrapService({})).toThrow('cold bootstrap dependencies are required');
});
test('serves evidence through the cluster route', async () => {
  const response = { json: jest.fn() };
  const evidence = jest.fn(async () => ({ node: 'a', active: false }));
  await expect(handleClusterRoute({ method: 'GET', path: '/api/v1/cluster/cold-bootstrap/evidence', request: {}, response, url: new URL('http://localhost'), getStatus: async () => ({}), getConfig: () => ({ elera: true }), coldEvidence: evidence })).resolves.toBe(true);
  expect(evidence).toHaveBeenCalled();
});
const nodes = [{ name: 'a', dataDir: '/a' }];
const state = { uuid: 'cluster', seqno: 1, safeToBootstrap: true };
test('plans and executes only after explicit confirmation', async () => { const bootstrap = jest.fn(); const service = createColdBootstrapService({ nodes, readState: async () => state, isOnline: async () => false, bootstrap }); await expect(service.plan()).resolves.toMatchObject({ eligible: true }); await expect(service.execute()).rejects.toMatchObject({ statusCode: 409 }); await expect(service.execute({ confirm: true })).resolves.toMatchObject({ candidate: { node: 'a' } }); expect(bootstrap).toHaveBeenCalledWith('a'); });
test('refuses an unsafe plan', async () => { const service = createColdBootstrapService({ nodes, readState: async () => ({ ...state, safeToBootstrap: false, seqno: -1 }), recover: async () => ({ uuid: 'cluster', seqno: -1 }), isOnline: async () => false, bootstrap: async () => {} }); await expect(service.execute({ confirm: true })).rejects.toMatchObject({ statusCode: 409 }); });
test('revalidates evidence immediately before bootstrap', async () => { let reads = 0; const bootstrap = jest.fn(); const service = createColdBootstrapService({ nodes, readState: async () => ({ ...state, seqno: ++reads }), isOnline: async () => false, bootstrap }); await expect(service.execute({ confirm: true })).rejects.toThrow('evidence changed'); expect(bootstrap).not.toHaveBeenCalled(); });
test('rejects a candidate that fails final verification', async () => { const service = createColdBootstrapService({ nodes, readState: async () => state, isOnline: async () => false, bootstrap: jest.fn(), verifyCandidate: async () => false }); await expect(service.execute({ confirm: true })).rejects.toThrow('revalidation failed'); });
test('rejects concurrent executions through a durable-style lock', async () => { let release; const lock = { run: async (operation) => { if (release) throw Object.assign(new Error('cold bootstrap already in progress'), { statusCode: 409 }); release = () => {}; try { return await operation(); } finally { release = undefined; } } }; let unblock; const bootstrap = jest.fn(() => new Promise((resolve) => { unblock = resolve; })); const service = createColdBootstrapService({ nodes, readState: async () => state, isOnline: async () => false, bootstrap, lock }); const first = service.execute({ confirm: true }); await new Promise((resolve) => setImmediate(resolve)); await expect(service.execute({ confirm: true })).rejects.toMatchObject({ statusCode: 409 }); unblock(); await first; });
test('returns the completed result for a repeated idempotency key', async () => { const bootstrap = jest.fn(); const service = createColdBootstrapService({ nodes, readState: async () => state, isOnline: async () => false, bootstrap }); const first = await service.execute({ confirm: true, idempotencyKey: 'op-1' }); const second = await service.execute({ confirm: true, idempotencyKey: 'op-1' }); expect(second).toEqual(first); expect(bootstrap).toHaveBeenCalledTimes(1); });
test('shares a concurrent idempotent operation instead of starting a second bootstrap', async () => { let release; const bootstrap = jest.fn(() => new Promise((resolve) => { release = resolve; })); const service = createColdBootstrapService({ nodes, readState: async () => state, isOnline: async () => false, bootstrap }); const first = service.execute({ confirm: true, idempotencyKey: 'same' }); await new Promise((resolve) => setImmediate(resolve)); const second = service.execute({ confirm: true, idempotencyKey: 'same' }); release(); await expect(Promise.all([first, second])).resolves.toHaveLength(2); expect(bootstrap).toHaveBeenCalledTimes(1); });
